# Generated by Django 4.0.2 on 2022-02-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dep_amount',
            fields=[
                ('id_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
    ]
