# Generated by Django 4.0.2 on 2022-02-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_pro', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_account',
        ),
        migrations.DeleteModel(
            name='dep_amount',
        ),
    ]
