# Generated by Django 4.0.2 on 2022-02-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_pro', '0004_delete_add_account_delete_dep_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
